---
- name: Add the user to wheel group
  user:
    name: "{{ssh_user}}"
    groups: wheel
    append: yes
  when: ansible_os_family == 'RedHat'

- name: check if authorized_keys file exists
  stat: path={{authorized_keys_file}}
  register: ssh_file_stat
  become: yes
  become_user: "{{ssh_user}}"

- block:
  - name: Create directory
    file:
      path: "{{ssh_dir}}"
      mode: '700'
      state: directory
  - name: Touch a file
    file:
      path: "{{authorized_keys_file}}"
      state: touch
      mode: '700'
  become: yes
  become_user: "{{ssh_user}}"
  when: not ssh_file_stat.stat.exists

- shell: echo "{{public_key}}" >> "{{authorized_keys_file}}"
  become: yes
  become_user: "{{ssh_user}}"

- name: SNOW_fetch_facts
  set_fact:
    ssh_user: "{{ssh_user}}"
