
---
- name: Test local
  gather_facts: False
  hosts: all
  tasks:

    - name: ping
      shell: ping -c 1 -w 2 8.8.8.8
      ignore_errors: true
    - shell: ip a s
      register: output1
    - debug:
        var: output1
      

