
---
- name: Test local
  hosts: localhost
  become: yes
  tasks:
    - name: Local host tasts
      cmd: whoami
      register: output
      
    - debug:
        msg: "{{ output }}"
      
- name: Test ansible on other node
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Other host tasts
      cmd: whoami
      register: output
      
    - debug:
        msg: "{{ output }}"
