- name: User | Add EDB user
  user: name={{ edb_user}} state=present

- name: filesystem | Create directories
  file: path={{ item.1.mntp }} state=directory owner={{ edb_user }} mode=775
  with_subelements:
    - "{{host_fs_layout}}"
    - filesystem

- name: filesystem | Create partition and pv
  shell:  parted -a optimal -s {{ item.1.device }} "mklabel gpt mkpart primary 1 -1"
  args:
    creates: "{{ item.1.pvname }}"
  with_subelements:
    - "{{host_fs_layout}}"
    - disk
  when: configure_host_disks and item.1.device != item.1.pvname

- name: filesystem | Create vg
  lvg: vg={{ item.vgname }} pvs={{ host_fs_layout_vgdisks }} state={{ item.state }}
  with_items: "{{host_fs_layout}}"
  when: configure_host_disks

- name: filesystem | create lv
  lvol: vg={{ item.0.vgname }} lv={{ item.1.lvname }} size={{ item.1.lvsize }} state=present shrink=no
  with_subelements:
    - "{{host_fs_layout}}"
    - filesystem
  when: configure_host_disks
  
- name: filesystem | create fs
  filesystem: fstype={{ item.1.fstype }} dev=/dev/{{ item.0.vgname }}/{{ item.1.lvname }} opts={{ item.1.fsopts | default(omit) }}
  with_subelements:
    - "{{host_fs_layout}}"
    - filesystem
  when: configure_host_disks

- name: filesytem | mount dir
  mount: name={{ item.1.mntp }} src=/dev/{{ item.0.vgname }}/{{ item.1.lvname }} dump=1 passno=2 fstype={{ item.1.fstype }} opts={{ item.1.mntopts | default(omit) }} state=mounted
  with_subelements:
    - "{{host_fs_layout}}"
    - filesystem
  when: configure_host_disks

- name: filesystem | Change permission on directories
  file: path={{ item.1.mntp }} state=directory owner={{ edb_user }}  mode=775
  with_subelements:
    - "{{host_fs_layout}}"
    - filesystem
