---
- name: testing ansible playbook
  hosts: all
  connection: local
#  vars:
#    db_machine_ip: 10.3.40.196
  tasks:
    - name: get the ip address
      set_fact:
        db_machine_ip: '{{ morpheus[''internalIp'']}}'
         #db_machine_ip: 192.168.9.136
    - debug:
        var: db_machine_ip
    - name: add host
      add_host:
        hostname: "{{ db_machine_ip }}"
        ansible_ssh_user: root
        ansible_ssh_pass: P@ssw0rd123
        groups: [ 'si-test' ]
- name: testing in target machine
  hosts: si-test
  become: true
#  vars:
#    ansible_python_interpreter: "/usr/bin/python"
  tasks:
    - ansible.builtin.file:
        path: /root/new_dir
        state: directory
        mode: '0755'
