---
- name: Create a VM from ISO Image and convert it to a Template
  hosts: localhost
  gather_facts: false
#  connection: local
  tasks:
   - set_fact:
      datacenter: C3
      datastore: datastore1
      db_template_name: Morpheus-DBAAS
      ora_db_version: 18.3.0.0
      guest_id: rhel7_64Guest
      si_template: true
      vcenter_ip: "192.168.9.70"
      vcenter_username: "administrator@vsphere.local"
      vcenter_password: "VMware1!"
      oracle_sw_source_www: 'http://192.168.9.136/files/orasw/'
      ansible_ssh_user: root
      ansible_ssh_pass: P@ssw0rd123
      db_machine_ip: 192.168.9.131

   - name: Create a virtual machine from a Custom ISO
     tags: never
     vmware_guest:
       hostname: "{{ vcenter_ip }}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       datacenter: "{{ datacenter }}"
       guest_id: "{{ guest_id }}"
       validate_certs: False
       folder: /VMs
       name: "{{ db_template_name }}"
       state: poweredon
       is_template: no
       disk:
       - size_gb: 60
         type: thin
         datastore: "{{ datastore }}"
       hardware:
         memory_mb: 8096
         num_cpus: 4
         memory_reservation_lock: True
         mem_limit: 8096
         mem_reservation: 4096
         cpu_limit: 8096
         cpu_reservation: 4096
         max_connections: 5
         hotadd_cpu: True
         hotremove_cpu: True
         hotadd_memory: True
         boot_firmware: "efi"
       cdrom:
           - controller_number: 0
             unit_number: 0
             state: present
             type: iso
             iso_path: "{{ iso_path }}"
       networks:
       - name: "{{ vswitch_name }}"
         device_type: vmxnet3
       wait_for_ip_address: yes
     delegate_to: localhost
     register: deploy
     until: deploy.instance.ipv4 is not none
     retries: 200
     delay: 5

   - debug:
      msg:  VM IP is "{{ deploy.instance.ipv4 }}"
     tags: never
   #- set_fact:
   #    db_machine_ip: "{{ deploy.instance.ipv4 }}"
   #  when: si_template

   - name: Adding db vm to inventory
     add_host:
       hostname: db-server
       ansible_ssh_host: "{{ db_machine_ip }}"
       ansible_ssh_port: 22
       ansible_ssh_user: root
       ansible_ssh_pass: P@ssw0rd123
     when: si_template

   - debug:
      msg={{ db_machine_ip }}
     when: si_template

   - name: Removing entry from known_hosts if any
     known_hosts:
       name: "{{ db_machine_ip }}"
       path: /root/.ssh/known_hosts
       state: absent
     when: si_template

- name: Oracle RDBMS Home Installation
  hosts: db-server
  vars:
   si_template: true
  become: yes
  roles:
  - { role: hpe-orahost, when: si_template }
  - { role: oraswdb-install, when: si_template }

- name: Relink libraries
  hosts: db-server
  tasks:
   - name: Relink libraries
     shell: /u01/app/oracle/{{ ora_db_version }}/db1-base/bin/relink all
     become: true
     become_user: oracle
     environment:
       ORACLE_BASE:  /u01/app/oracle
       ORACLE_HOME: /u01/app/oracle/{{ ora_db_version }}/db1-base
       PATH: /u01/app/oracle/{{ ora_db_version }}/db1-base/bin
       LD_LIBRARY_PATH: /u01/app/oracle/{{ ora_db_version }}/db1-base/lib
     when: si_template

   - name: Pause for 5 mins
     pause:
       minutes: 5

- name: Power off the VM and Create the Template
  hosts: localhost
#  become: yes
#  connection: local
  tasks:
   - name: Power off the VM for the Template Creation
     vmware_guest:
       hostname: "{{ vcenter_ip }}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       datacenter: "{{ datacenter }}"
       guest_id: "{{ guest_id }}"
       validate_certs: False
       name: "{{ db_template_name }}"
       state: poweredoff

   - name: Convert Database VM to Template
     vmware_guest:
       hostname: "{{ vcenter_ip }}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       datacenter: "{{ datacenter }}"
       guest_id: "{{ guest_id }}"
       validate_certs: False
       name: "{{ db_template_name }}"
       is_template: yes
       state: present
