---
- name: Create a VM from ISO Image and convert it to a Template
  hosts: all
  gather_facts: false
  connection: local
  tasks:
   - set_fact:
      datacenter: C3
      datastore: datastore1
      db_template_name: Morpheus-DBAASClone
      guest_id: rhel7
      si_template: false
      vcenter_ip: "192.168.9.70"
      vcenter_username: "administrator@vsphere.local"
      vcenter_password: "VMware1!"

