---
- name: Create a VM from a template
  hosts: localhost
  vars_files:
    - "./vars/edb_provision.yml"
  tasks:
  - name: Morpheus Fact
    set_fact:
      compatible_mode: '{{ morpheus[''customOptions''][''compatiblemode'']}}'
      db_name: '{{ morpheus[''customOptions''][''DBName'']}}'
      dynatune_profile: '{{ morpheus[''customOptions''][''workloadprofile'']}}'
      edb_version: '{{ morpheus[''customOptions''][''edbversion'']}}'
      edb_sub_version: '{{ morpheus[''customOptions''][''edb_subversion'']}}'
      input_password: '{{ morpheus[''customOptions''][''db_password'']}}'
      db_size: '{{ morpheus[''customOptions''][''pgdata_size'']}}'
      disk_number: '{{ morpheus[''customOptions''][''number_of_disks'']}}'
  - debug:
      var: compatible_mode
  - debug:
      var: db_name
  - debug:
      var: dynatune_profile
  - debug:
      var: edb_version
  - debug:
      var: input_password
  - debug:
      var: db_name
  - debug:
      var: db_size
  - debug:
      var: disk_number 
  - debug:
      msg: "hai"  
  - debug:
      var: ansible_ssh_pass
  - name: Adding db vm to inventory
    add_host:
      #hostname: "DBAASTEST005"
      hostname: "192.168.9.200"
      uuid: "4215d41f-e780-a5ee-4b4b-b6ccee65b615"
      ansible_ssh_user: "{{ ansible_ssh_user }}"
      ansible_ssh_pass: "{{ ansible_ssh_pass }}"
      groups: [ 'vmedbgroup' ]
    #with_items: "{{rac_nodes}}"
    ignore_errors: yes
    
- name: get disk names from host
  hosts: vmedbgroup
  tasks:
    - name: Testing the provisoned node
      shell: hostname
      register: output
    - debug:
        var: output

