---
- name: Add a user
  hosts: localhost
  gather_facts: false
  vars_files:
    - "./vars/edb_provision.yml"
  vars:
  - vm_name: "EDB_Deployed"
  - datacenter_name: "DBaaS_Datacenter"
  - folder_name : "/vm/"
  - cpu: 4
  - memory: 8192
  - vm_network: "VM Network"
  - datastore: "DBaaSMgmt_DS2"
  - vmware_cluster_name: "DBaaS_Cluster"
  - ssh_user: "root"
  - ssh_pass: "P@ssw0rd123"
  - db_size: "30"
  - disk_number: 1
  - tenant_name: hpedbaas
  - os_version: "RHEL 7.8"
  - dict_list: { cpu: "{{ cpu }}", memory: "{{ memory}}", db_size: "{{ db_size}}", disk_number: "{{ disk_number }}" }
  - template_dict: { "RHEL 7.8": "RHEL-RAC-MK", "RHEL 8": "RHEL-OS-8" }
  - rollback: true
  - uuids_val: []
  - nodes: 1 
  tasks:
    - name: Add User
      set_fact:
        compatible_mode: "{{ morpheus['customOptions']['compatiblemode'] }}"
        db_name: "{{ morpheus['customOptions']['DBName'] }}"
        dynatune_profile: "{{ morpheus['customOptions']['workloadprofile'] }}"
        edb_version: "{{ morpheus['customOptions']['edbversion'] }}"
        edb_sub_version: "{{ morpheus['customOptions']['edb_subversion'] }}"
        input_password: "{{ morpheus['customOptions']['db_password'] }}"
        db_size: "{{ morpheus['customOptions']['pgdata_size'] }}"
        disk_number: "{{ morpheus['customOptions']['number_of_disks'] }}"
    - debug:
        var: compatible_mode
    - debug:
        var: db_name
    - debug:
        var: dynatune_profile
    - debug:
        var: edb_version
    - debug:
        var: input_password
    - debug:
        var: db_name
    - debug:
        var: db_size
    - debug:
        var: disk_number 
