---
- name: Add a user
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add User
      set_fact:
        name: "{{ morpheus['customOptions']['pgdata_size'] }}"
    - debug:
        var: name
