---
- name: Create a VM from a template
  hosts: localhost

  tasks:
  - name: Morpheus server fact
    set_fact:
      uuid: '{{ morpheus[''server''][''uniqueId'']}}'
      vmname: '{{ morpheus[''server''][''name'']}}'
      db_machine_ip: '{{ morpheus[''internalIp'']}}'
  - debug:
      var: uuid
  - debug:
      var: vmname
  - debug:
      var: db_machine_ip
  
