---
- name: get vm details
  hosts: test
  tasks:
    - name: gather vm information
      set_fact:
        password: "{{ ansible_hostname }}"

    - name: print the values
      debug:
        var: password
  
