---
- name: Remove "{{ item }}"
  vmware_guest:
    hostname: "{{ vcenter_ip }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    uuid: "{{ item }}"
    state: absent
    force: yes
  run_once: true
  with_items: "{{uuids}}"
  delegate_to: localhost